server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_db_dev
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: classpath:db/migration